title: Devcafe
email: bjnhur@gmail.com
description: |
  변화를 위한 준비
baseurl: ''
url: 'http://devbj.com'

repository: bjnhur/bjnhur.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

gems:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

# iolo's custom
author: bjnhur@gmail.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: ''
#  ua: 'UA-72007721-1'
#facebook:
#  app_id: '1030557850293450'
#  username: bongjunhur
twitter:
  username: BongjunHur
google_plus:
  username: bjnhur
github:
  username: bjnhur
tistory:
  url: 'http://ts.devbj.com'
  
